2022-06-02 21:51:36,267 - root - INFO - Starting Bot...
2022-06-02 21:51:36,272 - apscheduler.scheduler - INFO - Scheduler started
2022-06-02 21:51:51,437 - root - INFO - User (ByDanimos) with ID: (358929628) entered the bot
2022-06-02 21:52:06,190 - root - ERROR - Update {'update_id': 116484466, 'message': {'date': 1654199525, 'chat': {'id': 358929628, 'username': 'ByDanimos', 'type': 'private', 'first_name': 'Dani'}, 'entities': [{'length': 5, 'type': 'bot_command', 'offset': 0}], 'photo': [], 'new_chat_members': [], 'channel_chat_created': False, 'caption_entities': [], 'supergroup_chat_created': False, 'message_id': 3, 'group_chat_created': False, 'new_chat_photo': [], 'delete_chat_photo': False, 'text': '/hoxe', 'from': {'id': 358929628, 'language_code': 'es', 'username': 'ByDanimos', 'is_bot': False, 'first_name': 'Dani'}}} caused error [Errno 2] No such file or directory: 'images/today.png'
2022-06-02 21:52:19,761 - root - INFO - Starting Bot...
2022-06-02 21:52:19,765 - apscheduler.scheduler - INFO - Scheduler started
2022-06-02 21:52:23,479 - root - ERROR - Update {'message': {'caption_entities': [], 'new_chat_members': [], 'channel_chat_created': False, 'entities': [{'offset': 0, 'length': 5, 'type': 'bot_command'}], 'date': 1654199542, 'photo': [], 'text': '/hoxe', 'supergroup_chat_created': False, 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'message_id': 5, 'chat': {'username': 'ByDanimos', 'id': 358929628, 'first_name': 'Dani', 'type': 'private'}, 'from': {'username': 'ByDanimos', 'id': 358929628, 'language_code': 'es', 'first_name': 'Dani', 'is_bot': False}}, 'update_id': 116484467} caused error [Errno 2] No such file or directory: 'images/today.png'
2022-06-02 21:53:00,929 - root - INFO - Starting Bot...
2022-06-02 21:53:00,932 - apscheduler.scheduler - INFO - Scheduler started
2022-06-02 21:53:03,670 - root - ERROR - Update {'update_id': 116484469, 'message': {'message_id': 9, 'channel_chat_created': False, 'new_chat_photo': [], 'chat': {'first_name': 'Dani', 'type': 'private', 'username': 'ByDanimos', 'id': 358929628}, 'new_chat_members': [], 'caption_entities': [], 'supergroup_chat_created': False, 'date': 1654199582, 'photo': [], 'text': '/hoxe', 'group_chat_created': False, 'entities': [{'length': 5, 'offset': 0, 'type': 'bot_command'}], 'delete_chat_photo': False, 'from': {'username': 'ByDanimos', 'first_name': 'Dani', 'id': 358929628, 'language_code': 'es', 'is_bot': False}}} caused error [Errno 2] No such file or directory: 'images/today.png'
2022-06-02 21:55:20,650 - root - INFO - Starting Bot...
2022-06-02 21:55:20,654 - apscheduler.scheduler - INFO - Scheduler started
2022-06-02 21:55:25,698 - root - ERROR - Update {'message': {'new_chat_members': [], 'message_id': 13, 'caption_entities': [], 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 5}], 'channel_chat_created': False, 'supergroup_chat_created': False, 'text': '/hoxe', 'photo': [], 'delete_chat_photo': False, 'chat': {'username': 'ByDanimos', 'id': 358929628, 'type': 'private', 'first_name': 'Dani'}, 'group_chat_created': False, 'new_chat_photo': [], 'date': 1654199723, 'from': {'is_bot': False, 'username': 'ByDanimos', 'language_code': 'es', 'first_name': 'Dani', 'id': 358929628}}, 'update_id': 116484471} caused error local variable 'day' referenced before assignment
2022-06-02 21:56:47,068 - root - INFO - Starting Bot...
2022-06-02 21:56:47,071 - apscheduler.scheduler - INFO - Scheduler started
2022-06-02 21:56:49,384 - root - ERROR - Update {'message': {'date': 1654199808, 'channel_chat_created': False, 'delete_chat_photo': False, 'message_id': 15, 'group_chat_created': False, 'new_chat_members': [], 'entities': [{'offset': 0, 'length': 5, 'type': 'bot_command'}], 'chat': {'username': 'ByDanimos', 'type': 'private', 'first_name': 'Dani', 'id': 358929628}, 'text': '/hoxe', 'new_chat_photo': [], 'supergroup_chat_created': False, 'photo': [], 'caption_entities': [], 'from': {'id': 358929628, 'language_code': 'es', 'is_bot': False, 'username': 'ByDanimos', 'first_name': 'Dani'}}, 'update_id': 116484472} caused error 'NoneType' object has no attribute 'from_user'
2022-06-02 21:57:06,406 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe9de0b43a0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot5211836413:AAG1qwnOqr_Q4XczGKM_SZlzpN29mKekgyY/getUpdates
2022-06-02 21:57:43,588 - root - INFO - Starting Bot...
2022-06-02 21:57:43,591 - apscheduler.scheduler - INFO - Scheduler started
2022-06-02 21:57:49,062 - root - ERROR - Update {'update_id': 116484474, 'message': {'message_id': 19, 'date': 1654199868, 'photo': [], 'text': '/hoxe', 'new_chat_photo': [], 'chat': {'username': 'ByDanimos', 'first_name': 'Dani', 'id': 358929628, 'type': 'private'}, 'supergroup_chat_created': False, 'group_chat_created': False, 'new_chat_members': [], 'caption_entities': [], 'channel_chat_created': False, 'entities': [{'type': 'bot_command', 'length': 5, 'offset': 0}], 'delete_chat_photo': False, 'from': {'language_code': 'es', 'username': 'ByDanimos', 'is_bot': False, 'first_name': 'Dani', 'id': 358929628}}} caused error 'NoneType' object has no attribute 'from_user'
2022-06-02 21:57:53,573 - root - ERROR - Update {'update_id': 116484476, 'message': {'message_id': 22, 'date': 1654199872, 'photo': [], 'text': '/hoxe', 'new_chat_photo': [], 'chat': {'username': 'ByDanimos', 'first_name': 'Dani', 'id': 358929628, 'type': 'private'}, 'supergroup_chat_created': False, 'group_chat_created': False, 'new_chat_members': [], 'caption_entities': [], 'channel_chat_created': False, 'entities': [{'type': 'bot_command', 'length': 5, 'offset': 0}], 'delete_chat_photo': False, 'from': {'language_code': 'es', 'username': 'ByDanimos', 'is_bot': False, 'first_name': 'Dani', 'id': 358929628}}} caused error 'NoneType' object has no attribute 'from_user'
2022-06-02 21:59:52,036 - root - INFO - Starting Bot...
2022-06-02 21:59:52,040 - apscheduler.scheduler - INFO - Scheduler started
2022-06-02 21:59:54,148 - root - ERROR - Update {'message': {'entities': [{'offset': 0, 'length': 5, 'type': 'bot_command'}], 'photo': [], 'text': '/hoxe', 'caption_entities': [], 'channel_chat_created': False, 'new_chat_members': [], 'supergroup_chat_created': False, 'group_chat_created': False, 'date': 1654199993, 'message_id': 24, 'chat': {'type': 'private', 'id': 358929628, 'username': 'ByDanimos', 'first_name': 'Dani'}, 'delete_chat_photo': False, 'new_chat_photo': [], 'from': {'is_bot': False, 'id': 358929628, 'username': 'ByDanimos', 'language_code': 'es', 'first_name': 'Dani'}}, 'update_id': 116484477} caused error Invalid file http url specified: unsupported url protocol
2022-06-02 22:01:04,959 - root - INFO - Starting Bot...
2022-06-02 22:01:04,963 - apscheduler.scheduler - INFO - Scheduler started
2022-06-02 22:01:07,332 - root - ERROR - Update {'update_id': 116484479, 'message': {'new_chat_photo': [], 'delete_chat_photo': False, 'entities': [{'type': 'bot_command', 'length': 5, 'offset': 0}], 'chat': {'type': 'private', 'username': 'ByDanimos', 'id': 358929628, 'first_name': 'Dani'}, 'date': 1654200066, 'channel_chat_created': False, 'text': '/hoxe', 'caption_entities': [], 'new_chat_members': [], 'group_chat_created': False, 'message_id': 28, 'supergroup_chat_created': False, 'photo': [], 'from': {'username': 'ByDanimos', 'is_bot': False, 'language_code': 'es', 'id': 358929628, 'first_name': 'Dani'}}} caused error Invalid file http url specified: unsupported url protocol
2022-06-02 22:01:44,346 - root - INFO - Starting Bot...
2022-06-02 22:01:44,350 - apscheduler.scheduler - INFO - Scheduler started
2022-06-02 23:28:23,844 - root - INFO - Starting Bot...
2022-06-02 23:28:23,848 - apscheduler.scheduler - INFO - Scheduler started
2022-06-02 23:38:38,914 - root - INFO - Starting Bot...
2022-06-02 23:38:38,917 - apscheduler.scheduler - INFO - Scheduler started
2022-06-02 23:40:53,269 - root - INFO - Starting Bot...
2022-06-02 23:40:53,272 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 00:13:45,281 - root - INFO - Starting Bot...
2022-06-03 00:13:45,286 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 00:17:27,594 - root - INFO - Starting Bot...
2022-06-03 00:17:27,598 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 00:18:00,845 - root - INFO - Starting Bot...
2022-06-03 00:18:00,850 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 11:30:39,115 - root - INFO - Starting Bot...
2022-06-03 11:30:39,119 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 11:30:45,009 - root - INFO - Starting Bot...
2022-06-03 11:30:45,016 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 13:21:52,181 - root - INFO - Starting Bot...
2022-06-03 13:21:52,185 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 13:22:24,268 - root - INFO - Starting Bot...
2022-06-03 13:22:24,271 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 13:23:48,000 - root - INFO - Starting Bot...
2022-06-03 13:23:48,004 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 13:24:23,709 - root - INFO - Starting Bot...
2022-06-03 13:24:23,713 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 13:32:10,449 - root - INFO - Starting Bot...
2022-06-03 13:32:10,453 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 13:34:54,892 - root - INFO - Starting Bot...
2022-06-03 13:34:54,896 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 13:37:24,967 - root - INFO - Starting Bot...
2022-06-03 13:37:24,972 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 13:41:58,617 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-06-03 13:41:58,620 - root - ERROR - Update None caused error urllib3 HTTPError ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-06-03 13:53:22,280 - root - INFO - Starting Bot...
2022-06-03 13:53:22,284 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 14:02:19,691 - root - INFO - Starting Bot...
2022-06-03 14:02:19,695 - apscheduler.scheduler - INFO - Scheduler started
2022-06-03 14:02:38,334 - root - INFO - Starting Bot...
2022-06-03 14:02:38,338 - apscheduler.scheduler - INFO - Scheduler started
